import { lib, game, ui, get, ai, _status } from '../../../../../noname.js'
export const character = {
	//在这里编写角色信息。
	character: {
		"re_boss_caocao": ["male", "wei", 12, ["shenhu", "boss_guixin", "xiongcai"], ["zhu", "boss", "bossallowed"]],
		"fusion_shen_sunce": ["male", "shen", "1/8", ["shenhu", "hunzi", "boss_jiang", "yingba", "scfuhai", "repinghe"], ["zhu", "boss", "bossallowed"]],
		"succubus": ["female", "shen", 6, ["meihun", "rebiyue", "yuehun", "yunshen", "boss_guimei", "yuxin"], ["zhu", "boss", "bossallowed"]],
		"re_boss_huatuo": ["male", "qun", 6, ["shenhu", "chulao", "mazui", "boss_shengshou", "guizhen", "wuqin"], ["zhu", "boss", "bossallowed"]],
		"re_boss_zhouyu": ["male", "wu", 10, ["shenhu", "huoshen", "boss_honglian", "boss_xianyin", "boss_zhaohuo", "boss_honglianx"], ["zhu", "boss", "bossallowed"]],
		"math_caojinyu": ["female", "wei", 10, ["shenhu", "math_yuqi", "math_shanshen", "math_xianjing"], ["zhu", "boss", "bossallowed"]],
		"norecover": ["male", "shen", 25, ["boss_fudu", "boss_kujiu", "boss_duqu", "boss_echou", "ex_haizhong"], ["zhu", "boss", "bossallowed"]],
		"fusion_xuhuang": ["male", "wei", 6, ["shenhu", "shipo", "famine", "olduanliang", "oljiezi"], ["zhu", "boss", "bossallowed"]],
		"liuxingyaodi": ["male", "shu", "6/8", ["shenhu", "renjun", "boss_rende"], ["zhu", "boss", "bossallowed"]],
		"re_boss_zhenji": ["female", "wei", 6, ["shenhu", "tashui", "lingbo", "jiaoxia", "fanghua", "reluoshen"], ["zhu", "boss", "bossallowed"]],
		"fusion_honglianpo": ["female", "shen", 8, ["boss_shiyou", "boss_wangshi", "boss_didong", "boss_guimei", "boss_xuechi"], ["zhu", "boss", "bossallowed"]],
		"ex_diaochan": ["female", "qun", 3, ["shenhu", "ex_yuhun", "ex_kongshen"], ["zhu", "boss", "bossallowed"]],
		"re_fusion_honglianpo": ["female", "shen", 8, ["boss_shiyou", "rewangshi", "boss_didong", "boss_guimei", "rexuechi"], ["zhu", "boss", "bossallowed"]],
		"zhizunwudi": ["male", "wu", 8, ["shenhu", "wuye", "boss_zhiheng"], ["zhu", "boss", "bossallowed"]],
		"luanshizhuhou": ["male", "qun", 10, ["shenhu", "qibing", "hunzhan"], ["zhu", "boss", "bossallowed"]],
		// "yitongjindi": ["male", "jin", 4, ["shenhu", "yuquan", "chengbing"], ["hiddenSkill", "zhu", "boss", "bossallowed"]],
		"re_nianshou": ["male", "shen", 4, ["boss_nianrui", "boss_mengtai", "boss_jingjue", "boss_renxing", "boss_ruizhi", "boss_nbaonu", "boss_shouyi"], ["zhu", "boss", "bossallowed"]],
		"barbarian_king": ["male", "qun", 10, ["shenhu", "equan", "manji", "manyi", "mansi", "xiangzhen", "huoshou", "zaiqi", "juxiang", "hanyong"], ["zhu", "boss", "bossallowed"]],
		"ex_yingzheng": ["male", "daqin", 8, ["shenhu", "ex_yitong", "ex_shihuang", "ex_liuhe", "ex_zulong", "ex_fenshu", "ex_kencao"], ["zhu", "boss", "bossallowed"]],
		"ex_zhaoji": ["female", "daqin", 4, ["ex_shanwu", "ex_daqi", "ex_xianji", "ex_huoluan"], ["zhu", "boss", "bossallowed", "forbidai"]],
		"ex_baiqi": ["male", "daqin", 8, ["shenhu", "ex_wuan", "ex_shashen", "ex_fachu", "ex_changsheng", "bubing_fangzhen", "qibing_liangju", "qibing_changjian", "ex_kencao", "nushou_jinnu"], ["zhu", "boss", "bossallowed"]],
		"ex_zhangyi": ["male", "daqin", 6, ["shenhu", "ex_lianheng", "ex_xiongbian", "ex_qiaoshe", "ex_xichu"], ["zhu", "boss", "bossallowed"]],
		"ex_shangyang": ["male", "daqin", 6, ["shenhu", "ex_bianfa", "ex_limu", "ex_kencao", "ex_lianzuo"], ["zhu", "boss", "bossallowed"]],
		"ex_zhaogao": ["male", "daqin", 6, ["shenhu", "ex_zhilu", "ex_gaizhao", "ex_haizhong", "ex_aili", "ex_zaiguan", "ex_kencao"], ["zhu", "boss", "bossallowed", "forbidai"]],
		"ex_miyue": ["female", "daqin", 8, ["shenhu", "ex_zhangzheng", "ex_taihou", "ex_youmie", "ex_yintui"], ["zhu", "boss", "bossallowed", "forbidai"]],
		"ex_lvbuwei": ["male", "daqin", 4, ["shenhu", "ex_jugu", "ex_qihuo", "ex_chunqiu", "ex_baixiang"], ["forbidai"]],
		"fusion_jiaxu": ["male", "qun", 7, ["rewansha", "reluanwu", "reweimu", "zhenlue", "fusion_jianshu", "fusion_yongdi"], ["zhu", "boss", "bossallowed", "forbidai"]],
		"fusion_liru": ["male", "qun", 5, ["shenhu", "juece", "mieji", "fencheng", "xinjuece", "xinmieji", "xinfencheng", "rejuece", "remieji", "fusion_zhudong", "fusion_cidu"], ["zhu", "boss", "bossallowed", "forbidai"]],
		"fusion_weiguojixie": ["none", "wei", 10, ["boss_jiguan", "boss_nailuo", "boss_didongjg", "boss_lianyujg", "boss_tunshi", "boss_tanshi"], ["zhu", "boss", "bossallowed"]],
		"fusion_shuguojixie": ["none", "shu", 15, ["boss_jiguan", "boss_yuhuojg", "boss_tianyun", "fusion_zhenwei", "fusion_benlei", "yizhong", "boss_lingyu", "boss_mojianjg"], ["zhu", "boss", "bossallowed"]],
		"fusion_shuguoyinghun": ["none", "shu", "1/2", ["shenhu", "fusion_gongshen", "boss_jingmiao", "boss_zhinang", "boss_biantian", "bazhen", "boss_lingfeng", "boss_jizhen", "boss_yuhuojg", "boss_qiwu", "boss_tianyujg", "boss_xiaorui", "boss_huchen", "boss_fengjian", "boss_keding"], ["zhu", "boss", "bossallowed"]],
		"fusion_shuguoyinghun2": ["none", "shu", "3/5", ["shenhu", "fusion_gongshen", "boss_jingmiao", "boss_zhinang", "boss_biantian", "bazhen", "boss_yuhuojg", "boss_qiwu", "boss_tianyujg"], ["zhu", "boss", "bossallowed"]],
		"fusion_weiguoyinghun": ["none", "wei", 10, ["shenhu", "boss_xuanlei", "boss_skonghun", "boss_chiying", "boss_chuanyun", "boss_leili", "boss_fengxing", "boss_jueji", "fusion_jiaoxie"], ["zhu", "boss", "bossallowed"]],
		"fusion_puyuan": ["male", "shu", 10, ["shenhu", "fusion_shengong", "olqisi", "pytianjiang", "fusion_zhuren", "fusion_bianshui"], ["zhu", "boss", "bossallowed"]],
		"fusion_shen_jiangwei": ["male", "shen", 10, ["shenhu", "jiufa", "fusion_tianren", "fusion_pingxiang", "fusion_tiaoxin", "olzhiji"], ["zhu", "boss", "bossallowed"]],
		"re_boss_yingzhao": ["male", "shen", 25, ["shenhu", "re_boss_yaoshou", "boss_fengdong", "boss_xunyou", "boss_sipu"], ["zhu", "boss", "bossallowed"]],
		"re_boss_xiangliu": ["male", "shen", 20, ["shenhu", "re_boss_yaoshou", "boss_duqu", "boss_jiushou", "re_boss_echou"], ["zhu", "boss", "bossallowed"]],
		"fusion_lingtong": ["male", "wu", 4, ["shenhu", "fusion_xuanfeng", "yongjin", "fusion_yinshi"], ["zhu", "boss", "bossallowed"]],
		"fusion_liuzan": ["male", "wu", 4, ["shenhu", "jsrgbahu", "kangyin", "fenyin", "refenyin", "fusion_liji"], ["zhu", "boss", "bossallowed"]],
		"math_xiahoujie": ["male", "wei", 8, ["shenhu", "math_liedan", "math_zhuangdan"], ["zhu", "boss", "bossallowed"]],
		"math_xushao": ["male", "qun", 6, ["shenhu", "math_pingjian"], ["zhu", "boss", "bossallowed"]],
		"math_zhangchangpu": ["female", "wei", 6, ["shenhu", "math_yanjiao", "math_xingshen"], ["zhu", "boss", "bossallowed"]],
		"fusion_zhuanlundizang": ["male", "shen", 8, ["boss_modao", "fusion_lunhui", "boss_wangsheng", "boss_zlfanshi", "boss_bufo", "fusion_wuliang", "boss_dayuan", "boss_diting"], ["zhu", "boss", "bossallowed"]],
		"fusion_shen_xunyu": ["male", "shen", 3, ["fusion_quhu", "fusion_jieming_all", "fusion_tianzuo", "fusion_lingce", "dinghan", "fusion_liuxiang"], ["zhu", "boss", "bossallowed"]],
		// "fusion_panshu": ["female", "wu", 3, ["shenhu", "fusion_weiyi", "jinzhi", "zhiren", "fusion_yaner"], ["zhu", "boss", "bossallowed"]],
		"re_boss_dongzhuo": ["male", "qun", 20, ["shenhu", "re_boss_qiangzheng", "boss_baolin", "oljiuchi", "roulin", "re_boss_hengzheng"], ["zhu", "boss", "bossallowed"]],
		// "re_boss_huangyueying": ["female", "qun", 4, ["shenhu", "boss_gongshen", "boss_jizhi", "qicai", "boss_guiyin"], ["zhu", "boss", "bossallowed"]],
		"fusion_shen_zhangfei": ["male", "shen", 6, ["shenhu", "fusion_shencai", "fusion_xunshi", "olpaoxiao"], ["zhu", "boss", "bossallowed"]],
		// "fusion_tengfanglan": ["female", "wu", 4, ["shenhu", "fusion_luochong_all", "dcaichen"], ["zhu", "boss", "bossallowed"]],
		// "math_tengfanglan": ["female", "wu", 4, ["shenhu", "fusion_luochong_all", "dcaichen"], ["zhu", "boss", "bossallowed"]] ,
		"math_beimihu": ["female", "qun", 3, ["shenhu", "math_zongkui", "math_guju", "math_baijia", "math_bmcanshi"], ["zhu", "boss", "bossallowed"]],
		"re_boss_lvbu": ["male", "qun", 6, ["re_boss_jingjia", "boss_aozhan", "mashu", "wushuang", "xiuluo", "shenwei", "shenji", "shenqu", "jiwu"], ["zhu", "boss", "bossallowed"]],
		"fusion_yuantanyuanxiyuanshang": ["male", "qun", 6, ["shenhu", "fusion_neifa"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_luzhi": ["male", "wei", "6/6/4", ["re_boss_lianyu", "drlt_qianjie", "qingzhong", "weijing", "re_boss_jingti", "zhichi", "aocai", "boss_baiyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_xusheng": ["male", "wu", "6/6/4", ["re_boss_lianyu", "xinpojun", "latest_ol_feiyang", "re_boss_shouyi", "oljiuchi", "jiushi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_huangzhong": ["male", "shu", "6/6/4", ["re_boss_lianyu", "xinliegong", "xinpojun", "re_boss_dungong", "wangong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_xiahouba": ["male", "shu", "6/6/4", ["re_boss_lianyu", "boss_qixiang", "baobian", "zhongyun", "jieyuan", "buqu", "boss_xiaoshou", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_kuailiangkuaiyue": ["male", "wei", "6/6/4", ["re_boss_lianyu", "drlt_qianjie", "nzry_jianxiang", "nzry_shenshi", "re_boss_moqu", "jugu", "re_boss_zhene", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_luxun": ["male", "wu", "6/6/4", ["re_boss_lianyu", "re_boss_liannu", "qianxun", "lianying", "sijian", "tairan", "qice", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_litong": ["male", "wei", "6/6/4", ["re_boss_lianyu", "tuifeng", "olcuipo", "xinbenxi", "re_boss_xiongshou", "jiaozi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_ganning": ["male", "wu", "6/6/4", ["re_boss_lianyu", "clanjiexuan", "fenwei", "latest_ol_feiyang", "luoying", "zhenlue", "re_boss_xiongshou", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_sunquan": ["male", "wu", "6/6/4", ["re_boss_lianyu", "re_boss_changandajian", "re_zhiheng", "fenwei", "latest_ol_feiyang", "dangxian", "shenshi", "xiangle", "clanjiejian", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_zhouyu": ["male", "wu", "5/5/4", ["re_boss_lianyu", "reyingzi", "refanjian", "luochong", "rekanpo", "fangzhu", "boss_jingmiao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_fuwan": ["male", "qun", "6/6/4", ["re_boss_lianyu", "re_boss_gudingdao", "moukui", "xinpojun", "re_boss_zhuishe", "zhenlue", "oljiuchi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_huaxiong": ["male", "qun", "10/10/4", ["re_boss_lianyu", "shiyong", "reyaowu", "shizhan", "weizhong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_zhangliao": ["male", "wei", "8/8/4", ["re_boss_lianyu", "re_boss_gudingdao", "re_boss_tengjia", "new_retuxi", "olzhiti", "olduorui", "xinpojun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_caozhang": ["male", "wei", "8/8/4", ["re_boss_lianyu", "rejiangchi", "weijing", "yingzi", "fulin", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_zhangling": ["male", "qun", "6/6/4", ["re_boss_lianyu", "zlhuji", "zlshoufu", "gzcongjian", "tairan", "boss_dayuan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_wangyi": ["female", "wei", "7/7/4", ["re_boss_lianyu", "zhenlie", "miji", "zhaxiang", "duwu", "xinkuanggu", "shibei", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_shen_zhaoyun": ["male", "shu", "6/6/4", ["re_boss_lianyu", "xinjuejing", "relonghun", "huxiao", "boss_moyany", "re_boss_kuangxi", "gzbuqu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_zhangliao2": ["male", "wei", "8/8/4", ["re_boss_lianyu", "new_retuxi", "relonghun", "paoxiao", "shangshi", "kangge", "re_boss_xianji", "zlhuji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_wuhu_huangzhong": ["male", "shu", "7/7/4", ["re_boss_lianyu", "re_boss_jinwuluorigong", "xinliegong", "xinfu_dianhu", "jieyuan", "re_boss_reborn_machao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_wuhu_machao": ["male", "shu", "7/7/4", ["re_boss_lianyu", "mashu", "retieji", "re_boss_dongdang", "re_boss_reborn_zhaoyun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_wuhu_zhaoyun": ["male", "shu", "7/7/4", ["re_boss_lianyu", "ollongdan", "olyajiao", "re_boss_dongdang", "re_boss_reborn_zhangfei", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_wuhu_zhangfei": ["male", "shu", "7/7/4", ["re_boss_lianyu", "olpaoxiao", "oltishen", "re_boss_dongdang", "jizhi", "re_boss_reborn_guanyu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_wuhu_guanyu": ["male", "shu", "7/7/4", ["re_boss_lianyu", "new_rewusheng", "new_yijue", "re_boss_dongdang", "oljiang", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_yanliangwenchou": ["male", "qun", "6/6/4", ["re_boss_lianyu", "olshuangxiong", "jiang", "xinkuanggu", "kunfen", "reluoyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_sp_pangde": ["male", "wei", "8/8/4", ["re_boss_lianyu", "mashu", "juesi", "kongcheng", "wushuang", "jiang", "reluoyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_hansui": ["male", "wei", "7/7/4", ["re_boss_lianyu", "olniluan", "olxiaoxi", "wushuang", "wushen", "tairan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_xiahoudun": ["male", "wei", "8/8/4", ["re_boss_lianyu", "buqu", "reganglie", "refankui", "boss_duqu", "gzyinghun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_daxiaoqiao": ["female", "wu", "7/7/4", ["re_boss_lianyu", "new_xingwu", "new_luoyan", "olhongyan", "jijiu", "jieyuan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_dengai": ["male", "wei", "8/8/4", ["re_boss_lianyu", "oltuntian", "olzaoxian", "shenxian", "xiongshu", "dzgengzhan", "yongjin", "jilei", "xuanlve", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_shen_zhangliao": ["male", "shen", "8/8/4", ["re_boss_lianyu", "olduorui", "olzhiti", "latest_ol_feiyang", "junxing", "tieji", "yuce", "re_boss_juejue", "gzyinghun", "re_boss_jueji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_zhangliang": ["male", "qun", "6/6/4", ["re_boss_lianyu", "xinleiji", "boss_luolei", "boss_leizhou", "olleijie", "boss_baiyi", "xinguidao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_shen_sunquan": ["male", "shen", "8/8/4", ["re_boss_lianyu", "junkyuheng", "junkdili", "qixi", "jiang", "keji", "zhuikong", "lianying", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_wutugu": ["male", "qun", "18/18/4", ["re_boss_lianyu", "re_boss_xiongshou2", "ranshang", "hanyong", "boss_luanchang", "xinkuanggu", "manjia", "sppanqin", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_yuejin": ["male", "wei", "7/7/4", ["re_boss_lianyu", "re_boss_xingtianpojunfu", "re_boss_heiguangkai", "xiaoguo", "xinshensu", "latest_ol_feiyang", "boss_aozhan", "re_boss_dungong", "re_boss_baoli", "reqicai", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_lidian": ["male", "wei", "6/6/4", ["re_boss_lianyu", "wangxi", "wangxi", "latest_ol_feiyang", "latest_ol_feiyang", "yise", "boss_fengdong", "re_boss_fanzhen", "re_boss_baoli", "new_keji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_caoxiancaohua1": ["female", "wei", "8/8/4", ["re_boss_lianyu", "wanrong", "xianwan", "lianhuo", "boss_suozu", "boss_nitai", "oltianxiang", "re_boss_baoli", "re_boss_nuyan", "re_boss_reborn_caoxiancaohua2", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
		"shanhetu_boss_caoxiancaohua2": ["female", "wei", "8/8/4", ["re_boss_lianyu", "huamu", "qianmeng", "liangyuan", "latest_ol_feiyang", "re_boss_dongdang", "boss_yuhuojg", "oljiuchi", "oltianxiang", "boss_lingqu", "re_boss_baoli", "re_boss_bamen"], ["zhu", "boss", "bossallowed"]],
	},

	translate: {
		// config
		"update": "更新情况",
		"thanks": "鸣谢",
		"warning": "警告",

		//classification
		"against7devil": "大战七阴",
		"against7devil_boss": "挑战boss加强包",
		"against7devil_fusion": "融包",
		"against7devil_math": "数包",
		"against7devil_ex": "扩包",

		//character
		"re_boss_caocao": "界魏武大帝",
		"fusion_shen_sunce": "界神孙策",
		"succubus": "魅魔",
		"re_boss_huatuo": "界药坛圣手",
		"re_boss_zhouyu": "界赤壁火神",
		"math_caojinyu": "数曹金玉",
		"norecover": "回血亡",
		"fusion_xuhuang": "融徐晃",
		"liuxingyaodi": "六星耀帝",
		"re_boss_zhenji": "界洛水仙子",
		"fusion_honglianpo": "红脸婆",
		"re_fusion_honglianpo": "界红脸婆",
		"ex_diaochan": "扩貂蝉",
		"zhizunwudi": "至尊吴帝",
		"luanshizhuhou": "乱世诸侯",
		// "yitongjindi": "一统晋帝",
		"re_nianshou": "界年兽",
		"barbarian_king": "蛮王",
		"ex_yingzheng": "扩嬴政",
		"ex_zhaoji": "扩赵姬",
		"ex_baiqi": "扩白起",
		"ex_zhangyi": "扩张仪",
		"ex_shangyang": "扩商鞅",
		"ex_zhaogao": "扩赵高",
		"ex_miyue": "扩芈月",
		"ex_lvbuwei": "扩吕不韦",
		"fusion_jiaxu": "融贾诩",
		"fusion_liru": "融李儒",
		"fusion_weiguojixie": "魏国机械",
		"fusion_shuguojixie": "蜀国机械",
		"fusion_shuguoyinghun": "蜀国英魂",
		"fusion_weiguoyinghun": "魏国英魂",
		"fusion_shuguoyinghun2": "蜀国智囊团",
		"fusion_puyuan": "融蒲元",
		"fusion_shen_jiangwei": "融神姜维",
		"re_boss_yingzhao": "界英招",
		"re_boss_xiangliu": "界相柳",
		"fusion_lingtong": "融凌统",
		"fusion_liuzan": "融留赞",
		"math_xiahoujie": "数夏侯杰",
		"math_xushao": "数许邵",
		"math_zhangchangpu": "数张昌蒲",
		"fusion_zhuanlundizang": "转轮地藏",
		"fusion_shen_xunyu": "融神荀彧",
		"fusion_panshu": "融潘淑",
		"re_boss_dongzhuo": "界乱世魔王",
		"fusion_shen_zhangfei": "融神张飞",
		"math_beimihu": "数卑弥呼",
		"re_boss_lvbu": "界虎牢关吕布",
		"fusion_yuantanyuanxiyuanshang": "融三袁",
		"shanhetu_boss_luzhi": "山河图鲁芝",
		"shanhetu_boss_xusheng": "江东铁壁",
		"shanhetu_boss_huangzhong": "羽林统帅",
		"shanhetu_boss_xiahouba": "山河图夏侯霸",
		"shanhetu_boss_kuailiangkuaiyue": "山河图蒯良蒯越",
		"shanhetu_boss_luxun": "山河图陆逊",
		"shanhetu_boss_litong": "山河图李通",
		"shanhetu_boss_ganning": "江表虎臣",
		"shanhetu_boss_sunquan": "东吴大帝",
		"shanhetu_boss_zhouyu": "山河图周瑜",
		"shanhetu_boss_fuwan": "山河图伏完",
		"shanhetu_boss_huaxiong": "山河图华雄",
		"shanhetu_boss_zhangliao": "山河图张辽",
		"shanhetu_boss_caozhang": "山河图曹彰",
		"shanhetu_boss_zhangling": "山河图张天师",
		"shanhetu_boss_wangyi": "决意巾帼",
		"shanhetu_boss_shen_zhaoyun": "常山赵子龙",
		"shanhetu_boss_zhangliao2": "古之召虎",
		"shanhetu_boss_wuhu_huangzhong": "五虎之黄忠",
		"shanhetu_boss_wuhu_machao": "五虎之马超",
		"shanhetu_boss_wuhu_zhaoyun": "五虎之赵云",
		"shanhetu_boss_wuhu_zhangfei": "五虎之张飞",
		"shanhetu_boss_wuhu_guanyu": "五虎之关羽",
		"shanhetu_boss_yanliangwenchou": "乱世双雄",
		"shanhetu_boss_sp_pangde": "山河图庞德",
		"shanhetu_boss_hansui": "山河图韩遂",
		"shanhetu_boss_xiahoudun": "山河图夏侯惇",
		"shanhetu_boss_daxiaoqiao": "绝代双骄",
		"shanhetu_boss_dengai": "伏鸾",
		"shanhetu_boss_shen_zhangliao": "山河图神张辽",
		"shanhetu_boss_zhangliang": "山河图张梁",
		"shanhetu_boss_shen_sunquan": "江东之虎",
		"shanhetu_boss_wutugu": "山河图兀突骨",
		"shanhetu_boss_yuejin": "山河图乐进",
		"shanhetu_boss_lidian": "山河图李典",
		"shanhetu_boss_caoxiancaohua1": "灵杉玉树",
		"shanhetu_boss_caoxiancaohua2": "灵杉玉树",
	},
	
}
