export const characters = {
	"re_boss_caocao": ["male", "wei", 12, ["shenhu", "boss_guixin", "xiongcai"], ["zhu", "boss", "bossallowed"]],
	"fusion_shen_sunce": ["male", "shen", "1/8", ["shenhu", "hunzi", "boss_jiang", "yingba", "scfuhai", "repinghe"], ["zhu", "boss", "bossallowed"]],
	"succubus": ["female", "shen", 6, ["meihun", "rebiyue", "yuehun", "yunshen", "boss_guimei", "yuxin"], ["zhu", "boss", "bossallowed"]],
	"re_boss_huatuo": ["male", "qun", 6, ["shenhu", "chulao", "mazui", "boss_shengshou", "guizhen", "wuqin"], ["zhu", "boss", "bossallowed"]],
	"re_boss_zhouyu": ["male", "wu", 10, ["shenhu", "huoshen", "boss_honglian", "boss_xianyin", "boss_zhaohuo", "boss_honglianx"], ["zhu", "boss", "bossallowed"]],
	"math_caojinyu": ["female", "wei", 10, ["shenhu", "math_yuqi", "math_shanshen", "math_xianjing"], ["zhu", "boss", "bossallowed"]],
	"norecover": ["male", "shen", 25, ["boss_fudu", "boss_kujiu", "boss_duqu", "boss_echou", "ex_haizhong"], ["zhu", "boss", "bossallowed"]],
	"fusion_xuhuang": ["male", "wei", 6, ["shenhu", "shipo", "famine", "olduanliang", "oljiezi"], ["zhu", "boss", "bossallowed"]],
	"liuxingyaodi": ["male", "shu", "6/8", ["shenhu", "renjun", "boss_rende"], ["zhu", "boss", "bossallowed"]],
	"re_boss_zhenji": ["female", "wei", 6, ["shenhu", "tashui", "lingbo", "jiaoxia", "fanghua", "reluoshen"], ["zhu", "boss", "bossallowed"]],
	"fusion_honglianpo": ["female", "shen", 8, ["boss_shiyou", "boss_wangshi", "boss_didong", "boss_guimei", "boss_xuechi"], ["zhu", "boss", "bossallowed"]],
	"ex_diaochan": ["female", "qun", 3, ["shenhu", "ex_yuhun", "ex_kongshen"], ["zhu", "boss", "bossallowed"]],
	"re_fusion_honglianpo": ["female", "shen", 8, ["boss_shiyou", "rewangshi", "boss_didong", "boss_guimei", "rexuechi"], ["zhu", "boss", "bossallowed"]],
	"zhizunwudi": ["male", "wu", 8, ["shenhu", "wuye", "boss_zhiheng"], ["zhu", "boss", "bossallowed"]],
	"luanshizhuhou": ["male", "qun", 10, ["shenhu", "qibing", "hunzhan"], ["zhu", "boss", "bossallowed"]],
	// "yitongjindi": ["male", "jin", 4, ["shenhu", "yuquan", "chengbing"], ["hiddenSkill", "zhu", "boss", "bossallowed"]],
	"re_nianshou": ["male", "shen", 4, ["boss_nianrui", "boss_mengtai", "boss_jingjue", "boss_renxing", "boss_ruizhi", "boss_nbaonu", "boss_shouyi"], ["zhu", "boss", "bossallowed"]],
	"barbarian_king": ["male", "qun", 10, ["shenhu", "equan", "manji", "manyi", "mansi", "xiangzhen", "huoshou", "zaiqi", "juxiang", "hanyong"], ["zhu", "boss", "bossallowed"]],
	"ex_yingzheng": ["male", "daqin", 8, ["shenhu", "ex_yitong", "ex_shihuang", "ex_liuhe", "ex_zulong", "ex_fenshu", "ex_kencao"], ["zhu", "boss", "bossallowed"]],
	"ex_zhaoji": ["female", "daqin", 4, ["ex_shanwu", "ex_daqi", "ex_xianji", "ex_huoluan"], ["zhu", "boss", "bossallowed", "forbidai"]],
	"ex_baiqi": ["male", "daqin", 8, ["shenhu", "ex_wuan", "ex_shashen", "ex_fachu", "ex_changsheng", "bubing_fangzhen", "qibing_liangju", "qibing_changjian", "ex_kencao", "nushou_jinnu"], ["zhu", "boss", "bossallowed"]],
	"ex_zhangyi": ["male", "daqin", 6, ["shenhu", "ex_lianheng", "ex_xiongbian", "ex_qiaoshe", "ex_xichu"], ["zhu", "boss", "bossallowed"]],
	"ex_shangyang": ["male", "daqin", 6, ["shenhu", "ex_bianfa", "ex_limu", "ex_kencao", "ex_lianzuo"], ["zhu", "boss", "bossallowed"]],
	"ex_zhaogao": ["male", "daqin", 6, ["shenhu", "ex_zhilu", "ex_gaizhao", "ex_haizhong", "ex_aili", "ex_zaiguan", "ex_kencao"], ["zhu", "boss", "bossallowed", "forbidai"]],
	"ex_miyue": ["female", "daqin", 8, ["shenhu", "ex_zhangzheng", "ex_taihou", "ex_youmie", "ex_yintui"], ["zhu", "boss", "bossallowed", "forbidai"]],
	"ex_lvbuwei": ["male", "daqin", 4, ["shenhu", "ex_jugu", "ex_qihuo", "ex_chunqiu", "ex_baixiang"], ["forbidai"]],
	"fusion_jiaxu": ["male", "qun", 7, ["rewansha", "reluanwu", "reweimu", "zhenlue", "fusion_jianshu", "fusion_yongdi"], ["zhu", "boss", "bossallowed", "forbidai"]],
	"fusion_liru": ["male", "qun", 5, ["shenhu", "juece", "mieji", "fencheng", "xinjuece", "xinmieji", "xinfencheng", "rejuece", "remieji", "fusion_zhudong", "fusion_cidu"], ["zhu", "boss", "bossallowed", "forbidai"]],
	"fusion_weiguojixie": ["none", "wei", 10, ["boss_jiguan", "boss_nailuo", "boss_didongjg", "boss_lianyujg", "boss_tunshi", "boss_tanshi"], ["zhu", "boss", "bossallowed"]],
	"fusion_shuguojixie": ["none", "shu", 15, ["boss_jiguan", "boss_yuhuojg", "boss_tianyun", "fusion_zhenwei", "fusion_benlei", "yizhong", "boss_lingyu", "boss_mojianjg"], ["zhu", "boss", "bossallowed"]],
	"fusion_shuguoyinghun": ["none", "shu", "1/2", ["shenhu", "fusion_gongshen", "boss_jingmiao", "boss_zhinang", "boss_biantian", "bazhen", "boss_lingfeng", "boss_jizhen", "boss_yuhuojg", "boss_qiwu", "boss_tianyujg", "boss_xiaorui", "boss_huchen", "boss_fengjian", "boss_keding"], ["zhu", "boss", "bossallowed"]],
	"fusion_shuguoyinghun2": ["none", "shu", "3/5", ["shenhu", "fusion_gongshen", "boss_jingmiao", "boss_zhinang", "boss_biantian", "bazhen", "boss_yuhuojg", "boss_qiwu", "boss_tianyujg"], ["zhu", "boss", "bossallowed"]],
	"fusion_weiguoyinghun": ["none", "wei", 10, ["shenhu", "boss_xuanlei", "boss_skonghun", "boss_chiying", "boss_chuanyun", "boss_leili", "boss_fengxing", "boss_jueji", "fusion_jiaoxie"], ["zhu", "boss", "bossallowed"]],
	"fusion_puyuan": ["male", "shu", 10, ["shenhu", "fusion_shengong", "olqisi", "pytianjiang", "fusion_zhuren", "fusion_bianshui"], ["zhu", "boss", "bossallowed"]],
	"fusion_shen_jiangwei": ["male", "shen", 10, ["shenhu", "jiufa", "fusion_tianren", "fusion_pingxiang", "fusion_tiaoxin", "olzhiji"], ["zhu", "boss", "bossallowed"]],
	"re_boss_yingzhao": ["male", "shen", 25, ["shenhu", "re_boss_yaoshou", "boss_fengdong", "boss_xunyou", "boss_sipu"], ["zhu", "boss", "bossallowed"]],
	"re_boss_xiangliu": ["male", "shen", 20, ["shenhu", "re_boss_yaoshou", "boss_duqu", "boss_jiushou", "re_boss_echou"], ["zhu", "boss", "bossallowed"]],
	"fusion_lingtong": ["male", "wu", 4, ["shenhu", "fusion_xuanfeng", "yongjin", "fusion_yinshi"], ["zhu", "boss", "bossallowed"]],
	"fusion_liuzan": ["male", "wu", 4, ["shenhu", "jsrgbahu", "kangyin", "fenyin", "refenyin", "fusion_liji"], ["zhu", "boss", "bossallowed"]],
	"math_xiahoujie": ["male", "wei", 8, ["shenhu", "math_liedan", "math_zhuangdan"], ["zhu", "boss", "bossallowed"]],
	"math_xushao": ["male", "qun", 6, ["shenhu", "math_pingjian"], ["zhu", "boss", "bossallowed"]],
	"math_zhangchangpu": ["female", "wei", 6, ["shenhu", "math_yanjiao", "math_xingshen"], ["zhu", "boss", "bossallowed"]],
	"fusion_zhuanlundizang": ["male", "shen", 8, ["boss_modao", "fusion_lunhui", "boss_wangsheng", "boss_zlfanshi", "boss_bufo", "fusion_wuliang", "boss_dayuan", "boss_diting"], ["zhu", "boss", "bossallowed"]],
	"fusion_shen_xunyu": ["male", "shen", 3, ["fusion_quhu", "fusion_jieming_all", "fusion_tianzuo", "fusion_lingce", "dinghan", "fusion_liuxiang"], ["zhu", "boss", "bossallowed"]],
	// "fusion_panshu": ["female", "wu", 3, ["shenhu", "fusion_weiyi", "jinzhi", "zhiren", "fusion_yaner"], ["zhu", "boss", "bossallowed"]],
	"re_boss_dongzhuo": ["male", "qun", 20, ["shenhu", "re_boss_qiangzheng", "boss_baolin", "oljiuchi", "roulin", "re_boss_hengzheng"], ["zhu", "boss", "bossallowed"]],
	// "re_boss_huangyueying": ["female", "qun", 4, ["shenhu", "boss_gongshen", "boss_jizhi", "qicai", "boss_guiyin"], ["zhu", "boss", "bossallowed"]],
	"fusion_shen_zhangfei": ["male", "shen", 6, ["shenhu", "fusion_shencai", "fusion_xunshi", "olpaoxiao"], ["zhu", "boss", "bossallowed"]],
	// "fusion_tengfanglan": ["female", "wu", 4, ["shenhu", "fusion_luochong_all", "dcaichen"], ["zhu", "boss", "bossallowed"]],
	// "math_tengfanglan": ["female", "wu", 4, ["shenhu", "fusion_luochong_all", "dcaichen"], ["zhu", "boss", "bossallowed"]] ,
	"math_beimihu": ["female", "qun", 3, ["shenhu", "math_zongkui", "math_guju", "math_baijia", "math_bmcanshi"], ["zhu", "boss", "bossallowed"]],
	"re_boss_lvbu": ["male", "qun", 6, ["re_boss_jingjia", "boss_aozhan", "mashu", "wushuang", "xiuluo", "shenwei", "shenji", "shenqu", "jiwu"], ["zhu", "boss", "bossallowed"]],
	"fusion_yuantanyuanxiyuanshang": ["male", "qun", 6, ["shenhu", "fusion_neifa"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_luzhi": ["male", "wei", "6/6/4", ["re_boss_lianyu", "drlt_qianjie", "qingzhong", "weijing", "re_boss_jingti", "zhichi", "aocai", "boss_baiyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_xusheng": ["male", "wu", "6/6/4", ["re_boss_lianyu", "xinpojun", "latest_ol_feiyang", "re_boss_shouyi", "oljiuchi", "jiushi", "xinluoshen", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_huangzhong": ["male", "shu", "6/6/4", ["re_boss_lianyu", "xinliegong", "xinpojun", "re_boss_dungong", "wangong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_xiahouba": ["male", "shu", "6/6/4", ["re_boss_lianyu", "boss_qixiang", "baobian", "zhongyun", "jieyuan", "buqu", "boss_xiaoshou", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_kuailiangkuaiyue": ["male", "wei", "6/6/4", ["re_boss_lianyu", "drlt_qianjie", "nzry_jianxiang", "nzry_shenshi", "re_boss_moqu", "jugu", "re_boss_zhene", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_luxun": ["male", "wu", "6/6/4", ["re_boss_lianyu", "equip_zhugeliannu", "qianxun", "lianying", "sijian", "tairan", "qice", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_litong": ["male", "wei", "6/6/4", ["re_boss_lianyu", "tuifeng", "olcuipo", "xinbenxi", "re_boss_xiongshou", "jiaozi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_ganning": ["male", "wu", "6/6/4", ["re_boss_lianyu", "clanjiexuan", "fenwei", "latest_ol_feiyang", "luoying", "zhenlue", "re_boss_xiongshou", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_sunquan": ["male", "wu", "6/6/4", ["re_boss_lianyu", "equip_changandajian", "re_zhiheng", "fenwei", "latest_ol_feiyang", "dangxian", "shenshi", "xiangle", "clanjiejian", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_zhouyu": ["male", "wu", "5/5/4", ["re_boss_lianyu", "reyingzi", "refanjian", "luochong", "rekanpo", "fangzhu", "boss_jingmiao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_fuwan": ["male", "qun", "6/6/4", ["re_boss_lianyu", "equip_gudingdao", "moukui", "xinpojun", "re_boss_zhuishe", "zhenlue", "oljiuchi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_huaxiong": ["male", "qun", "10/10/4", ["re_boss_lianyu", "shiyong", "reyaowu", "shizhan", "weizhong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_zhangliao": ["male", "wei", "8/8/4", ["re_boss_lianyu", "equip_gudingdao", "equip_tengjia", "new_retuxi", "olzhiti", "olduorui", "xinpojun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_caozhang": ["male", "wei", "8/8/4", ["re_boss_lianyu", "rejiangchi", "weijing", "yingzi", "fulin", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_zhangling": ["male", "qun", "6/6/4", ["re_boss_lianyu", "zlhuji", "zlshoufu", "gzcongjian", "tairan", "boss_dayuan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_wangyi": ["female", "wei", "7/7/4", ["re_boss_lianyu", "zhenlie", "miji", "zhaxiang", "duwu", "xinkuanggu", "shibei", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_shen_zhaoyun": ["male", "shu", "6/6/4", ["re_boss_lianyu", "xinjuejing", "relonghun", "huxiao", "boss_moyany", "re_boss_kuangxi", "gzbuqu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_zhangliao2": ["male", "wei", "8/8/4", ["re_boss_lianyu", "new_retuxi", "relonghun", "paoxiao", "shangshi", "kangge", "re_boss_xianji", "zlhuji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_wuhu_huangzhong": ["male", "shu", "7/7/4", ["re_boss_lianyu", "equip_jinwuluorigong", "xinliegong", "xinfu_dianhu", "jieyuan", "re_boss_reborn_machao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_wuhu_machao": ["male", "shu", "7/7/4", ["re_boss_lianyu", "mashu", "retieji", "re_boss_dongdang", "re_boss_reborn_zhaoyun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_wuhu_zhaoyun": ["male", "shu", "7/7/4", ["re_boss_lianyu", "ollongdan", "olyajiao", "re_boss_dongdang", "re_boss_reborn_zhangfei", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_wuhu_zhangfei": ["male", "shu", "7/7/4", ["re_boss_lianyu", "olpaoxiao", "oltishen", "re_boss_dongdang", "jizhi", "re_boss_reborn_guanyu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_wuhu_guanyu": ["male", "shu", "7/7/4", ["re_boss_lianyu", "new_rewusheng", "new_yijue", "re_boss_dongdang", "oljiang", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_yanliangwenchou": ["male", "qun", "6/6/4", ["re_boss_lianyu", "olshuangxiong", "jiang", "xinkuanggu", "kunfen", "reluoyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_sp_pangde": ["male", "wei", "8/8/4", ["re_boss_lianyu", "mashu", "juesi", "kongcheng", "wushuang", "jiang", "reluoyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_hansui": ["male", "wei", "7/7/4", ["re_boss_lianyu", "olniluan", "olxiaoxi", "wushuang", "wushen", "tairan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_xiahoudun": ["male", "wei", "8/8/4", ["re_boss_lianyu", "buqu", "reganglie", "refankui", "boss_duqu", "gzyinghun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_daxiaoqiao": ["female", "wu", "7/7/4", ["re_boss_lianyu", "new_xingwu", "new_luoyan", "olhongyan", "jijiu", "jieyuan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_dengai": ["male", "wei", "8/8/4", ["re_boss_lianyu", "oltuntian", "olzaoxian", "shenxian", "xiongshu", "dzgengzhan", "yongjin", "jilei", "xuanlve", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_shen_zhangliao": ["male", "shen", "8/8/4", ["re_boss_lianyu", "olduorui", "olzhiti", "latest_ol_feiyang", "junxing", "tieji", "yuce", "re_boss_juejue", "gzyinghun", "re_boss_jueji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_zhangliang": ["male", "qun", "6/6/4", ["re_boss_lianyu", "xinleiji", "boss_luolei", "boss_leizhou", "olleijie", "boss_baiyi", "xinguidao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_shen_sunquan": ["male", "shen", "8/8/4", ["re_boss_lianyu", "junkyuheng", "junkdili", "qixi", "jiang", "keji", "zhuikong", "lianying", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_wutugu": ["male", "qun", "18/18/4", ["re_boss_lianyu", "re_boss_xiongshou2", "ranshang", "hanyong", "boss_luanchang", "xinkuanggu", "manjia", "sppanqin", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_yuejin": ["male", "wei", "7/7/4", ["re_boss_lianyu", "equip_xingtianpojunfu", "equip_heiguangkai", "xiaoguo", "xinshensu", "latest_ol_feiyang", "boss_aozhan", "re_boss_dungong", "re_boss_baoli", "reqicai", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_lidian": ["male", "wei", "6/6/4", ["re_boss_lianyu", "wangxi", "wangxi", "latest_ol_feiyang", "latest_ol_feiyang", "yise", "boss_fengdong", "re_boss_fanzhen", "re_boss_baoli", "new_keji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_caoxiancaohua1": ["female", "wei", "8/8/4", ["re_boss_lianyu", "wanrong", "xianwan", "lianhuo", "boss_suozu", "boss_nitai", "oltianxiang", "re_boss_baoli", "re_boss_nuyan", "re_boss_reborn_caoxiancaohua2", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_caoxiancaohua2": ["female", "wei", "8/8/4", ["re_boss_lianyu", "huamu", "qianmeng", "liangyuan", "latest_ol_feiyang", "re_boss_dongdang", "boss_yuhuojg", "oljiuchi", "oltianxiang", "boss_lingqu", "re_boss_baoli", "re_boss_bamen"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_yanliangwenchou2": ["male", "qun", "8/8/4", ["re_boss_lianyu", "olshuangxiong", "new_reluoyi", "jiang", "fengpo", "wushuang", "boss_sipu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_caiyong": ["male", "qun", "8/8/4", ["re_boss_lianyu", "bizhuan", "tongbo", "re_boss_chenghu", "re_boss_xuli", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_jushou": ["male", "qun", "8/8/4", ["re_boss_lianyu", "equip_zhugeliannu", "jianying", "shibei", "zhaxiang", "oljizhan", "zhichi", "reqicai", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_lushi": ["female", "qun", "8/8/4", ["re_boss_lianyu", "olzhuyan", "olleijie", "boss_dayuan", "sgkuanggu", "nzry_huaiju", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_shamoke": ["male", "shu", "8/8/4", ["re_boss_lianyu", "gzjili", "zishu", "boss_zhaohuo", "longdan", "chongzhen", "re_boss_shennu", "reganglie", "re_boss_baoli", "re_boss_zhufang", "boss_renxing", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_yuanshao": ["male", "qun", "8/8/4", ["re_boss_lianyu", "luanji", "hanyong", "jizhi", "zhenlve", "re_boss_juexing", "jugu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_lvbu": ["male", "qun", "8/8/4", ["re_boss_lianyu", "equip_wushuangfangtianji", "equip_hongmianbaihuapao", "equip_shufazijinguan", "latest_ol_feiyang", "baonu", "wumou", "ol_wuqian", "ol_shenfen", "xinjuejing", "reqicai", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_dongzhuo": ["male", "qun", "12/12/4", ["re_boss_lianyu", "oljiuchi", "roulin", "benghuai", "jieming", "oldianjun", "ninge", "re_boss_juexing2", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_huangzu": ["male", "qun", "8/8/4", ["re_boss_lianyu", "olcuorui", "wangong", "new_reluoyi", "rejianxiong", "reganglie", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_xusheng2": ["male", "wu", "8/8/4", ["re_boss_lianyu", "equip_gudingdao", "xinpojun", "latest_ol_feiyang", "re_boss_shouyi", "oljiuchi", "jiushi", "zhengding", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_lvmeng": ["male", "wu", "6/6/4", ["re_boss_lianyu", "equip_zhugeliannu", "keji", "qinxue", "botu", "jugu", "keshou", "chouhai", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_yingzhao": ["male", "yao", "6/6/4", ["re_boss_lianyu", "boss_fengdong", "boss_xunyou", "boss_sipu", "aocai", "gzcongjian", "re_boss_shouyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_duanjiong": ["male", "qun", "7/7/4", ["re_boss_lianyu", "olsaogu", "luoying", "qixi", "tairan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_qiongqi": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_zhue", "boss_futai", "re_boss_eyi", "boss_yandu", "shenxian", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_shuishengonggong": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_juehong", "boss_lingqu", "re_boss_eyi", "repojun", "xinjuece", "shanzhuan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_hundun": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_wuzang", "boss_xiangde", "re_boss_eyi", "re_boss_yinzei", "paoxiao", "oljiang", "xinkuanggu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_taowu": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_nitai", "boss_minwan", "re_boss_eyi", "boss_luanchang_switch", "zhendu", "boss_lingqu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_taotie": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_tanyu", "boss_cangmu", "re_boss_eyi", "boss_jicai_switch", "chouhai", "keshou", "jiaozi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_ganning2": ["male", "wu", "6/6/4", ["re_boss_lianyu", "latest_ol_feiyang", "qixi", "fenwei", "gzduanliang", "reluoshen", "xiehui", "mingzhe", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_jiangdong_yanrou": ["male", "wei", "7/7/4", ["re_boss_lianyu", "equip_wushuangfangtianji", "choutao", "xiangshu", "retieji", "lieren", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_haiheshang1": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_qixiang", "boss_tanyu", "boss_jicai_switch", "re_boss_baoyu", "jieyuan", "re_boss_xuzhang", "xinfu_gongqing", "chouhai", "benyu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_haiheshang2": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_qixiang", "boss_tanyu", "boss_jicai_switch", "re_boss_baoyu", "drlt_jueyan", "re_boss_xuzhang", "tuxing", "xinlvli", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_haiheshang3": ["male", "yao", "20/20/4", ["re_boss_lianyu", "boss_qixiang", "boss_tanyu", "boss_jicai_switch", "ranshang", "enyuan", "re_boss_xuzhang", "re_boss_yangwu", "zhaxiang", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_haiheshang4": ["male", "yao", "7/7/4", ["re_boss_lianyu", "boss_qixiang", "boss_tanyu", "boss_jicai_switch", "re_boss_baoyu", "clanjiexuan", "re_boss_xuzhang", "re_boss_xianji", "zhengding", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_sanshiyou": ["male", "yao", "7/7/4", ["re_boss_lianyu", "re_boss_eyi", "re_boss_sanku", "re_boss_rensan", "reyicong", "tuntian", "zaoxian", "re_boss_wangliang_blue", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_yuanniu": ["male", "yao", "8/8/4", ["re_boss_lianyu", "qianxi", "clbshuiyong", "re_boss_zhangdu", "yidu", "jieyuan", "re_boss_huangkong", "xinenyuan", "re_boss_juexing", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_xiangliujushe": ["male", "yao", "9/9/4", ["re_boss_lianyu", "re_boss_yaoshou", "re_boss_duqu", "re_boss_bashou", "re_boss_sishe", "jiaozi", "re_boss_zaie", "chouhai", "re_boss_moqu", "re_boss_bamen", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_baihu": ["male", "yao", "8/8/4", ["re_boss_lianyu", "qianxi", "yimie", "reyaowu", "olxiaoxi", "cuijue", "re_boss_wuying", "re_boss_xianji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_kuileiguowang": ["male", "yao", "9/9/4", ["re_boss_lianyu", "drlt_qianjie", "hezhong", "qice", "boss_tunshi", "jianying", "lianying", "re_boss_zhene", "re_boss_zhufang", "re_boss_duanhun", "re_boss_reborn_yaosengzhenjia", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_yaosengzhenjia": ["male", "yao", "9/9/4", ["re_boss_lianyu", "drlt_qianjie", "reguhuo", "clansankuang", "re_boss_cuanchao", "re_boss_dongdang", "re_boss_youji", "re_boss_luanxin", "shanduan", "yilie", "dangxian", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_feiduan": ["male", "yao", "8/8/4", ["re_boss_lianyu", "qiangxi", "yangkuang", "re_boss_busi", "re_boss_juexing", "xinkuanggu", "re_boss_xietu", "reqiaomeng", "rejianxiong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_chijianwuzhe": ["male", "yao", "8/8/4", ["re_boss_lianyu", "equip_qimenbagua", "equip_sanlve", "choutao", "xinkuanggu", "re_boss_shihun", "zhengding", "yilie", "olzhuiji", "re_boss_tonghua", "ollongdan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_shenlouyaoshi": ["male", "yao", "9/9/4", ["re_boss_lianyu", "qianhuan", "boss_fengdong", "re_boss_jinghua", "rejizhi", "reqicai", "nuzhan", "re_boss_huanyue", "boss_zhinang", "sijian", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_lingji": ["female", "yao", "9/9/4", ["re_boss_lianyu", "latest_ol_feiyang", "bingxin", "boss_fengdong", "re_boss_juepan", "xinwanyi", "boss_mengtai", "rebiyue", "re_boss_zhouxue", "boss_xuechi", "qhzhangji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_yixin": ["male", "yao", "9/9/4", ["re_boss_lianyu", "latest_ol_feiyang", "re_boss_tiepao", "re_boss_taidao", "re_boss_changqiang", "zhongyi", "re_boss_yongjue", "re_boss_jiansheng", "zhihu", "oljianhe", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_gulong": ["male", "yao", "8/8/4", ["re_boss_lianyu", "shensu", "zhengding", "kongcheng", "shiyuan", "yizhao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_baiyannv": ["female", "yao", "9/9/4", ["re_boss_lianyu", "guanxu", "sidao", "re_boss_jimu", "jiang", "boss_chiyi", "zhengding", "re_boss_shenshi", "re_boss_juexing", "relonghun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_moluoyecha": ["male", "yao", "9/9/4", ["re_boss_lianyu", "kongcheng", "yuanchou", "re_boss_sanyi", "boss_jingmiao", "boss_yuhuojg", "zhidao", "re_boss_yuren", "re_boss_wuying", "re_boss_juejue", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_yao_xiangliujushe2": ["male", "yao", "10/10/4", ["re_boss_lianyu", "boss_mengtai", "re_boss_yaoshou", "boss_duqu", "re_boss_bashou", "drlt_zhenggu", "kongcheng", "xueji", "re_boss_zaie", "boss_echou", "re_boss_jingti", "chouhai", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_fadong_liusandao": ["male", "qun", "7/7/4", ["re_boss_lianyu", "chongzhen", "boss_huchen", "boss_aozhan", "nuzhan", "wuqian", "zhanshen", "dengji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_weiyan": ["male", "shu", "8/8/4", ["re_boss_lianyu", "equip_qinggangjian", "equip_baiyinshizi", "xinkuanggu", "qimou", "zishu", "xuanlve", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_zhaoyun": ["male", "shu", "8/8/4", ["re_boss_lianyu", "ollongdan", "chongzhen", "reyingzi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_zhanghe": ["male", "qun", "8/8/4", ["re_boss_lianyu", "spolzhouxuan", "qice", "latest_ol_feiyang", "kongcheng", "mengjin", "re_boss_cuiku", "aocai", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_lijue": ["male", "qun", "8/8/4", ["re_boss_lianyu", "xinfu_langxi", "xinfu_yisuan", "latest_ol_feiyang", "bazhen", "xinlvli", "xinfu_weilu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_pangde": ["male", "qun", "8/8/4", ["re_boss_lianyu", "mashu", "rejianchu", "latest_ol_feiyang", "jilei", "mengjin", "luoying", "olninge", "re_boss_juexing", "oljiang", "re_boss_zhengyi", "re_boss_chengxiong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_lvmeng": ["male", "wu", "8/8/4", ["re_boss_lianyu", "xinpojun", "juece", "latest_ol_feiyang", "xinenyuan", "choutao", "youyan", "shanduan", "re_boss_juexing", "re_boss_zhengyi", "huisheng", "xinfu_fuyin", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_guohuai": ["male", "wei", "7/7/4", ["re_boss_lianyu", "rejingce", "rebotu", "zhiheng", "fulin", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_wanglang": ["male", "wei", "7/7/4", ["re_boss_lianyu", "gushi", "shibei", "jici", "tianbian", "zhichi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_zhuling": ["male", "wei", "8/8/4", ["re_boss_lianyu", "jixian", "wushuang", "latest_ol_feiyang", "re_boss_xiongshou", "shichou", "zhaxiang", "boss_lunhui", "boss_xiongshou", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_hanzhong_zhangchunhua": ["female", "wei", "8/8/4", ["re_boss_lianyu", "gangzhi", "shangshi", "zhaxiang", "duwu", "aocai", "boss_futai", "zhendu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_jiangwei": ["male", "shu", "7/7/8", ["re_boss_lianyu", "equip_hanbingjian", "olsbzhuri", "olsbranji", "yingyang", "sanku", "tianbian", "re_boss_shunxue", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_yanyan": ["male", "shu", "5/5/5", ["re_boss_lianyu", "equip_renwangdun", "nzry_juzhan", "yimie", "drlt_wanglie", "re_boss_busi", "re_boss_tiepao", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_huojun": ["male", "shu", "5/5/5", ["re_boss_lianyu", "equip_baiyinshizi", "qiongshou", "tuxing", "drlt_poshi", "luanfeng", "re_boss_zhouxue", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_machao": ["male", "shu", "7/7/8", ["re_boss_lianyu", "equip_zhangbashemao", "retieji", "xinleiji", "ganglie", "sgkuanggu", "boss_dayuan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_zhangfei": ["male", "shu", "7/7/8", ["re_boss_lianyu", "equip_baiyinshizi", "olpaoxiao", "oltishen", "zhongyi", "oljiang", "wangxi", "re_boss_juexing", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_wuqiao": ["male", "qun", "8/8/8", ["re_boss_lianyu", "equip_qinggangjian", "clanqiajue", "clanmuyin", "shenzhi", "olxianzhen", "re_boss_sishe", "shanzhuan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_wuyi": ["male", "shu", "8/8/8", ["re_boss_lianyu", "equip_zhugeliannu", "equip_shufazijinguan", "xinbenxi", "jieyuan", "bixin", "wangong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_duanjiong": ["male", "qun", "8/8/8", ["re_boss_lianyu", "equip_zhangbashemao", "olsaogu", "re_zhiheng", "xiangle", "re_boss_fumeng", "re_boss_lingdong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_zhujun": ["male", "qun", "8/8/8", ["re_boss_lianyu", "equip_guanshifu", "olcuipo", "new_rewusheng", "ganglie", "re_boss_bamen", "re_boss_zhengyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_hansui": ["male", "qun", "8/8/8", ["re_boss_lianyu", "equip_guanshifu", "niluan", "xiaoxi", "luanji", "xinkuanggu", "re_boss_duanjia", "re_boss_changqiang", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_lingcao": ["male", "wu", "8/8/8", ["re_boss_lianyu", "equip_tengjia", "dujin", "yimie", "re_boss_duanjia", "re_boss_jibao", "drlt_jueyan", "tuxing", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_shamoke": ["male", "shu", "7/7/8", ["re_boss_lianyu", "equip_pintieshuangji", "gzjili", "latest_ol_feiyang", "fentian", "zishu", "huaiyuan", "re_boss_libing", "re_boss_duanjia", "boss_nbaonu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_liangxing": ["male", "qun", "7/7/8", ["re_boss_lianyu", "lulve", "lxzhuixi", "latest_ol_feiyang", "faen", "jiushi", "boss_lingqu", "hengjiang", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_chengjichengcui": ["male", "wei", "7/7/8", ["re_boss_lianyu", "oltousui", "olchuming", "latest_ol_feiyang", "xiansi", "shizhan", "cangxin", "boss_qixiang", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_xiahoudun": ["male", "wei", "7/7/8", ["re_boss_lianyu", "reganglie", "new_qingjian", "latest_ol_feiyang", "tiandu", "huituo", "xinleiji", "youdi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_xushu": ["male", "shu", "7/7/8", ["re_boss_lianyu", "equip_zhangbashemao", "zhuhai", "qianxin", "repojun", "gzcongjian", "lulve", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_tenglong": ["male", "shen", "7/7/8", ["re_boss_lianyu", "equip_baiyinshizi", "latest_ol_chenlong", "xianshuai", "re_boss_fushen", "re_boss_tengyun", "re_boss_juexing", "xinfu_weilu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_yuejin": ["male", "wei", "7/7/8", ["re_boss_lianyu", "equip_baiyinshizi", "gzcongjian", "qiaoyan", "re_boss_juexing", "xinfu_weilu", "re_boss_shunxue", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_lvmeng": ["male", "wu", "6/6/8", ["re_boss_lianyu", "equip_hanbingjian", "shelie", "gongxin", "xinguidao", "rejingce", "olbeige", "nzry_shicai", "xinfu_sidao", "re_boss_liezhen", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_wenyang": ["male", "wei", "8/8/8", ["re_boss_lianyu", "equip_chiyanzhenhunqin", "xinlvli", "choujue", "reganglie", "zhongyun", "yangkuang", "boss_jiushou", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_xuzhu": ["male", "wei", "7/7/8", ["re_boss_lianyu", "equip_guanshifu", "new_reluoyi", "latest_ol_feiyang", "oljiang", "juguan", "retieji", "jiwu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_zhuhuan": ["male", "wu", "7/7/8", ["re_boss_lianyu", "equip_jinwuluorigong", "equip_renwangdun", "equip_tianjitu", "fenli", "pingkou", "xuanlve", "boss_mengtai", "gz_keji", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_sunjian": ["male", "wu", "7/8/8", ["re_boss_lianyu", "yinghun", "wulie", "latest_ol_feiyang", "kunfen", "enyuan", "bazhen", "langxi", "shangshi", "boss_chuanyun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_shoushangdebaihu": ["male", "shen", "9/10/9", ["re_boss_lianyu", "boss_xiongshou", "xinkuanggu", "boss_xiongshou", "boss_sipu", "re_boss_shouhun", "re_boss_shouhun", "boss_fengdong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_jiededaofei": ["male", "qun", "9/10/9", ["re_boss_lianyu", "equip_hanbingjian", "duodao", "olzhanjin", "re_boss_jielve", "olqiangxi", "xinkuanggu", "zhaxiang", "re_boss_bamen", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_junshi_shibixie": ["male", "qun", "9/9/9", ["re_boss_lianyu", "equip_renwangdun", "boss_wuzang", "zhengu", "jiaozi", "re_boss_baozhu", "dzgengzhan", "bixiong", "re_boss_zhouxue", "re_boss_zhengyi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_yangyi": ["male", "shu", "5/5/5", ["re_boss_lianyu", "dingcuo", "oljuanxia", "xiansi", "danshou", "mengjin", "boss_tianyun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_guojia": ["male", "wei", "5/5/5", ["re_boss_lianyu", "equip_zhugeliannu", "equip_bagua", "tiandu", "yiji", "oldangxian", "huituo", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_yuejin": ["male", "wei", "5/5/5", ["re_boss_lianyu", "xiaoguo", "oljiangchi", "oldangxian", "qiaoli", "re_boss_yingzi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_guanyu": ["male", "wei", "5/5/5", ["re_boss_lianyu", "re_boss_wusheng", "re_boss_mashu", "nuzhan", "yijue", "xinkuanggu", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_caoxiu": ["male", "wei", "5/5/5", ["re_boss_lianyu", "equip_qilingong", "qianju", "qingxi", "liegong", "jieyuan", "anjian", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_wangyi": ["female", "wei", "5/5/5", ["re_boss_lianyu", "equip_qinglong", "olzhenlie", "olmiji", "shouxi", "xiangle", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_gongsunzan": ["male", "qun", "5/5/5", ["re_boss_lianyu", "olsbjiaodi", "olsbbaojing", "boss_chuanyun", "oldangxian", "jiaozi", "wushen", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_chengyu": ["male", "wei", "5/5/5", ["re_boss_lianyu", "equip_bagua", "shefu", "benyu", "oltishen", "re_boss_yiji", "ollongdan", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_zhangliao": ["male", "qun", "5/5/5", ["re_boss_lianyu", "equip_hanbingjian", "olzhengbing", "jsrgtuwei", "new_retuxi", "qixi", "xiansi", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_mayuanyi": ["male", "qun", "8/8/6", ["re_boss_lianyu", "jibing", "wangjing", "moucuan", "olfuhun", "qingxi", "jijiu", "repojun", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
	"shanhetu_beiwang_zhangmancheng": ["male", "qun", "8/8/6", ["re_boss_lianyu", "equip_guofengyupao", "re_boss_yingzi", "boss_modao", "re_boss_sidao", "qiangwu", "re_boss_jianxiong", "re_boss_baoli"], ["zhu", "boss", "bossallowed"]],
}
